### ISSUE TITLE
Google Assignments External Tool not working

### ISSUE THREAD

**Issue by PCaso27301** [themesalmond/moodle-theme_almondb#13]
I have several Google Assignments (LTI External Tool activities) in my course and when I switched to the Almondb theme, they no longet display their contents, There is a thin window which appears to be one text line in height which appears to be trying to load the content, but it's too small to do anything with.

I can create or modify a tool as usual, but it won't display for the teacher or for the students.

**Comment by themesalmond** [comment]
Hello,
Please share a screenshot with us so we can assist you further.

**Comment by PCaso27301** [comment]
![TeacherView](https://user-images.githubusercontent.com/68242460/200414514-bd88aba2-8ba7-41ba-b32f-84e4d69641fd.PNG)
![StudentView](https://user-images.githubusercontent.com/68242460/200414519-b6f06f80-dd38-4c15-b977-c69959aaf173.PNG)
The top is the view from the teacher (no scroll bar even). The bottom is what the students see. Normally, the window would be open to view without scrolling.

**Comment by themesalmond** [comment]
Hi, thanks for sharing the screenshot. We are working on the problem. If you don't mind, can you share your course backup with us? We need this so we can test it. You can reach us by e-mail at support@themesalmond.com.
Best Regards.

**Comment by PCaso27301** [comment]
https://www.dropbox.com/sh/nog4klt7kdoq7vy/AAANdOGvJMjHUs7o8KWDbU3Ba?dl=0 
Let me know if the share doesn't work. I backed up without user information. Thanks.

**Comment by themesalmond** [comment]
Hello,
Thanks for your sharing.
The problem is with the screen resolution. We found that there were no problems at large resolutions. Moodle automatically adjusts the height according to the resolution. While student has no problems in view, there is compression with scroll in teacher. This is because the tools I marked take up extra space. We're going to solve the little problem there by shrinking the course image a little bit. You can follow the updates.

Best Regards.

![ss_1](https://user-images.githubusercontent.com/107366277/200823673-f30d185b-a83a-4284-a19c-aadebc90e579.png)
![ss_2](https://user-images.githubusercontent.com/107366277/200823947-6614ea48-30e8-44f1-8c39-da9d5c25e564.png)

**Comment by PCaso27301** [comment]
Thank you! That will be most helpful.

Paula

**Comment by PCaso27301** [comment]
Just ran the update and changed to the compact logo and the problem is fixed. Thank you so much for the quick fix!

 

Paula





Paula L. Caso
Mathematics & Computer Science
North Olmsted High School
27301 Butternut Ridge Road
North Olmsted, Ohio 44070
Phone: 440/588-5800
WWW: https://www.NOHSteachers.info
