### ISSUE TITLE
Contact Form does not send message

### ISSUE THREAD

**Issue by Boakyesn** [themesalmond/moodle-theme_almondb#22]
I have installed V4.2+ which the contact form does not work. When you click on the submit button it just takes you to the homepage without sending the inputted message. It also does not give any feedback when the submit button is clicked. My Moodle version is 4.2.1

**Comment by themesalmond** [comment]
We use the moodle support form. We are careful not to change anything in the core. To activate the contact form we showed in the previous mail on your login screen
Check the Site administration > Server > Support availability settings

**Comment by themesalmond** [comment]
Navigate to > Site administration > Server > Email > Outgoing mail configuration
Go to Section SMTP security and select to “None”.
Also Contact form uses moodle features. We are careful not to change anything in the core. To activate the contact form we showed in the previous mail on your login screen
Check the Site administration > Server > Support availability settings > Available
Go to the login screen of your site. 

Try again to send an e-mail from contact site support by pressing the question mark 

If the e-mail sending is successful after selecting "None", this indicates that it is caused by a problem with your hosting. (SSL and TLS) You can contact your hosting service.

**Comment by Boakyesn** [comment]
It works now............thank you
