### ISSUE TITLE
Missing settings in course administration

### ISSUE THREAD

**Issue by DanielSulea** [themesalmond/moodle-theme_almondb#37]
Hello,

As an admin, there are some settings that I am missing to properly administer a course.

I only see this menu at the top in AlmondB: 

![image](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/29ee122f-10ca-4903-882d-bc81fe5a27e0)

But I don’t see the following:

![image](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/9dc532a1-3e40-4c4b-be44-044c58b07660)

Also, I can’t access the course administration panel:

![image](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/7bc3c62b-8351-492d-b038-c67a532943e0)

These pictures are taken from a different theme in Moodle, not AlmondB.

Could you please advise?

Many thanks and kind regards

**Comment by themesalmond** [comment]
Hello,
What are you using which moodle version?

**Comment by DanielSulea** [comment]
Hi,

we are using [Moodle](http://moodle.org/) [4.3.2+ (Build: 20240119)](https://moodledev.io/general/releases)

Kind regards,
Daniel

**Comment by themesalmond** [comment]
Hello,
The features you mentioned are probably features of the other theme you are using. These is not features belonging to Moodle, you will not find them in almondb.
More precisely, they gathered the features in moodle together with a different design. Doing this will cause difficulties in subsequent updates because you are changing the moodle core. That's why in almondb we avoid adding features that change moodle itself.
Best Regards

**Comment by DanielSulea** [comment]
Hello,

thank you for reply.

Best Regards,
Daniel
